linters-settings:
 gocyclo:
   min-complexity: 20
 gocognit:
   min-complexity: 30
 funlen:
   lines: 45
 nestif:
   min-complexity: 3
 dupl:
   threshold: 50
 maintidx:
   under: 35

linters:
 # Disable all linters.
 # Default: false
 disable-all: true
 # Enable specific linter
 # https://golangci-lint.run/usage/linters/#enabled-by-default
 enable:
   - gocyclo
   - gocognit
   - funlen
   - nestif
   - dupl
   - maintidx

run:
  skip-files:
    - ".*_test\\.go$"
